name: Makefile CI

on:
  push:
    branches: [ "main", "wip-client-server" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format

    - name: Format code
      run: clang-format -i $(find . -name '*.c' -o -name '*.h')

    - name: Check code format
      run: clang-format --dry-run --Werror $(find . -name '*.c' -o -name '*.h')

    - name: Build project
      run: make
